version: '3'

services:
  db:
    image: postgres
  web:
    image: oak
    build: .
    command: python3 oak/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  migrations:
    image: oak
    command: python3 oak/manage.py migrate --noinput
    volumes:
      - .:/code
