# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.CharField(choices=[(b'X', b'X'), (b'O', b'O')], max_length=1)),
                ('to_field', models.CharField(choices=[(b'X', b'X'), (b'O', b'O')], max_length=1)),
                ('player', models.CharField(choices=[(b'X', b'X'), (b'O', b'O')], max_length=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oak.Game')),
            ],
        ),
    ]
