# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oak', '0002_auto_20170801_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='from_column',
            field=models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='to_column',
            field=models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2')], max_length=1),
        ),
    ]
