# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oak', '0003_auto_20170801_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='from_row',
            field=models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2')], default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamelog',
            name='to_row',
            field=models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2')], default='0', max_length=1),
            preserve_default=False,
        ),
    ]
