# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oak', '0005_auto_20170801_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='player',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O')], max_length=1),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='to_column',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='to_row',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1),
        ),
    ]
